apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/shopflow_orders"
  SECRET_KEY: "shopflow-super-secret-key"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
