replicaCount: 1

image:
  repository: 731872836849.dkr.ecr.ap-south-1.amazonaws.com/shopflow/product-service
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"
