apiVersion: v1
kind: ConfigMap
metadata:
  name: shopflow-config
  namespace: shopflow
data:
  AUTH_SERVICE_URL: "http://auth-service:3001"
  PRODUCT_SERVICE_URL: "http://product-service:3002"
  ORDER_SERVICE_URL: "http://order-service:3003"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REACT_APP_API_URL: "http://api-gateway:8080"
