apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopflow
  namespace: argocd
  labels:
    app: shopflow
spec:
  project: default
  source:
    repoURL: https://github.com/harsh1505/shopflow
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: shopflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
